name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Install dependencies
      run: make -j8

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
